// <auto-generated />
using System;
using EndlasNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EndlasNet.Data.Migrations
{
    [DbContext(typeof(EndlasNetDbContext))]
    [Migration("20201214211952_IntermediateParamAndQuoteMigration")]
    partial class IntermediateParamAndQuoteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EndlasNet.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointOfContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EndlasNet.Data.LaserQuoteSession", b =>
                {
                    b.Property<int>("LaserQuoteSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("QuoteSessionId")
                        .HasColumnType("int");

                    b.HasKey("LaserQuoteSessionId");

                    b.HasIndex("QuoteSessionId");

                    b.ToTable("LaserQuoteSession");
                });

            modelBuilder.Entity("EndlasNet.Data.MachineQuoteSession", b =>
                {
                    b.Property<int>("MachineQuoteSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("QuoteSessionId")
                        .HasColumnType("int");

                    b.HasKey("MachineQuoteSessionId");

                    b.HasIndex("QuoteSessionId");

                    b.ToTable("MachineQuoteSession");
                });

            modelBuilder.Entity("EndlasNet.Data.QuoteSession", b =>
                {
                    b.Property<int>("QuoteSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuoteSessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuoteSessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuoteSessionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("QuoteSessions");
                });

            modelBuilder.Entity("EndlasNet.Data.RawMaterial", b =>
                {
                    b.Property<int>("RawMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("CladLayerDensity")
                        .HasColumnType("float");

                    b.Property<double>("FlowRateSlope")
                        .HasColumnType("float");

                    b.Property<double>("FlowRateYIntercept")
                        .HasColumnType("float");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowderFeeder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PowderLayerPrice")
                        .HasColumnType("float");

                    b.Property<string>("PowderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RawMaterialId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("EndlasNet.Data.RawMaterial_LaserQuoteSession", b =>
                {
                    b.Property<int>("LaserQuoteSessionId")
                        .HasColumnType("int");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.HasKey("LaserQuoteSessionId", "RawMaterialId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("RawMaterial_LaserQuoteSession");
                });

            modelBuilder.Entity("EndlasNet.Data.LaserQuoteSession", b =>
                {
                    b.HasOne("EndlasNet.Data.QuoteSession", "QuoteSession")
                        .WithMany()
                        .HasForeignKey("QuoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteSession");
                });

            modelBuilder.Entity("EndlasNet.Data.MachineQuoteSession", b =>
                {
                    b.HasOne("EndlasNet.Data.QuoteSession", "QuoteSession")
                        .WithMany()
                        .HasForeignKey("QuoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteSession");
                });

            modelBuilder.Entity("EndlasNet.Data.QuoteSession", b =>
                {
                    b.HasOne("EndlasNet.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EndlasNet.Data.RawMaterial_LaserQuoteSession", b =>
                {
                    b.HasOne("EndlasNet.Data.LaserQuoteSession", "LaserQuoteSession")
                        .WithMany("RawMat_LasQuoteSes")
                        .HasForeignKey("LaserQuoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndlasNet.Data.RawMaterial", "RawMaterial")
                        .WithMany("RawMat_LasQuoteSes")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaserQuoteSession");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("EndlasNet.Data.LaserQuoteSession", b =>
                {
                    b.Navigation("RawMat_LasQuoteSes");
                });

            modelBuilder.Entity("EndlasNet.Data.RawMaterial", b =>
                {
                    b.Navigation("RawMat_LasQuoteSes");
                });
#pragma warning restore 612, 618
        }
    }
}
